FROM apache/airflow:2.8.1
USER root
RUN apt-get update && apt-get install -y --no-install-recommends gcc && apt-get clean
USER airflow
ENV DBT_PROFILES_DIR=/opt/airflow/dbt
ENV PATH="/home/airflow/.local/bin:${PATH}"
RUN pip install --no-cache-dir \
	airflow-clickhouse-plugin \
	clickhouse-driver \
	dbt-core \
	dbt-clickhouse