erDiagram
    %%====================
    %% DIMENSIONS
    %%====================

    DIM_DEVICE {
        int DeviceKey PK
        string Brand "NOT NULL"
        string Model "NOT NULL"
        float MinPower "CHECK (>=0)"
        float MaxPower "CHECK (>=MinPower)"
        date InstallationDate "NOT NULL"
        date ValidTo "DEFAULT '9999-12-31'"
    }

    DIM_LOCATION {
        int LocationKey PK
        string DeviceLocation "NOT NULL"
        string ClosestWeatherStation "NOT NULL"
        string PricingRegion "NOT NULL"
        date ValidFrom "NOT NULL"
        date ValidTo "DEFAULT '9999-12-31'"
    }

    DIM_TIME {
        int TimeKey PK
        date FullDate "NOT NULL"
        int Year "CHECK (>=2000)"
        int Month "CHECK (1-12)"
        int Day "CHECK (1-31)"
        int DayOfWeek "CHECK (1-7)"
        int HourOfDay "CHECK (0-23)"
        string Season "CHECK IN {Winter,Spring,Summer,Autumn}"
        boolean IsHoliday "DEFAULT false"
        boolean IsWeekend "DEFAULT false"
        boolean IsPeakHour "DEFAULT false"
    }

    %%====================
    %% FACT TABLE
    %%====================

    FACT_HEATING_ENERGY_USAGE {
        int FactID PK
        int TimeKey FK "NOT NULL"
        int DeviceKey FK "NOT NULL"
        int LocationKey FK "NOT NULL"
        float ElectricityPrice "CHECK (>=0)"
        float ASHP_Power "CHECK (>=0)"
        float Boiler_Power "CHECK (>=0)"
        float Air_Drier_Power "CHECK (>=0)"
        float Boiler_Voltage "CHECK (>=0)"
        float IndoorTemp
        float IndoorHumidityPerc "CHECK (0<=value<=100)"
        float IndoorHumidityAbs
        float WC_HumidityAbs
        float WC_Temp
        float OutdoorTemp
        float DewPoint
        float OutdoorHumidityPerc "CHECK (0<=value<=100)"
        float CloudCoverage "CHECK (0<=value<=100)"
        float UV_index "CHECK (>=0)"
        float AirPressure_mmHg "CHECK (>=600 AND <=800)"
        float WindDir "CHECK (0<=value<360)"
        float WindGustSpeed_ms "CHECK (>=0)"
        float WindSpeed_ms "CHECK (>=0)"
        string WeatherCondition
    }

    %%====================
    %% RELATIONSHIPS
    %%====================

    FACT_HEATING_ENERGY_USAGE ||--|| DIM_TIME : "TimeKey"
    FACT_HEATING_ENERGY_USAGE }|--|| DIM_DEVICE : "DeviceKey"
    FACT_HEATING_ENERGY_USAGE }|--|| DIM_LOCATION : "LocationKey"
