version: 2

models:
  - name: fact_heating_energy_usage
    description: "Heating energy usage facts for devices and locations"
    columns:
      - name: FactKey
        description: "Unique row identifier"
      - name: TimeKey
        description: "Foreign key to time dimension"
      - name: DeviceKey
        description: "Foreign key to device dimension"
      - name: LocationKey
        description: "Foreign key to location dimension"
      - name: hour_start
        description: "Hour start timestamp"
      - name: ElectricityPrice
        description: "Electricity price at the time"
      - name: ASHP_Power
        description: "Power consumption of ASHP system"
      - name: Boiler_Power
        description: "Power consumption of the boiler"
      - name: Air_Drier_Power
        description: "Power consumption of air drier"
      - name: Boiler_Voltage
        description: "Boiler voltage"
      - name: IndoorTemp
        description: "Indoor temperature (째C)"
      - name: IndoorHumidityPerc
        description: "Indoor humidity percentage"
      - name: IndoorHumidityAbs
        description: "Indoor absolute humidity"
      - name: WC_HumidityAbs
        description: "WC absolute humidity"
      - name: WC_Temp
        description: "WC temperature (째C)"
      - name: OutdoorTemp
        description: "Outdoor temperature (째C)"
      - name: DewPoint
        description: "Calculated dew point (째C)"
      - name: OutdoorHumidityPerc
        description: "Outdoor humidity percentage"
      - name: CloudCoverage
        description: "Cloud coverage percentage"
      - name: UV_Index
        description: "UV index level"
      - name: AirPressure_mmHg
        description: "Air pressure in millimeters of mercury"
      - name: WindDir
        description: "Wind direction (degrees)"
      - name: WindGustSpeed_ms
        description: "Wind gust speed (m/s)"
      - name: WindSpeed_ms
        description: "Average wind speed (m/s)"
      - name: WeatherCondition
        description: "Weather condition description"

    tests:
      # --- Custom data validity tests ---
      - expression_is_true_clickhouse:
          arguments:
            column_name: ASHP_Power
            expression: "ASHP_Power >= 0"

      - expression_is_true_clickhouse:
          arguments:
            column_name: IndoorHumidityPerc
            expression: "IndoorHumidityPerc BETWEEN 0 AND 100"

      - expression_is_true_clickhouse:
          arguments:
            column_name: OutdoorHumidityPerc
            expression: "OutdoorHumidityPerc BETWEEN 0 AND 100"

      - expression_is_true_clickhouse:
          arguments:
            column_name: UV_Index
            expression: "UV_Index >= 0"

      - expression_is_true_clickhouse:
          arguments:
            column_name: AirPressure_mmHg
            expression: "AirPressure_mmHg BETWEEN 600 AND 800"

      - expression_is_true_clickhouse:
          arguments:
            column_name: WindDir
            expression: "WindDir BETWEEN 0 AND 360"

      - expression_is_true_clickhouse:
          arguments:
            column_name: WindSpeed_ms
            expression: "WindSpeed_ms >= 0"

      - expression_is_true_clickhouse:
          arguments:
            column_name: WindGustSpeed_ms
            expression: "WindGustSpeed_ms >= 0"

      # --- Basic null checks ---
      - not_null:
          column_name: ASHP_Power
      - not_null:
          column_name: DeviceKey
      - not_null:
          column_name: LocationKey
      - not_null:
          column_name: TimeKey
