FROM apache/airflow:2.8.1
USER root
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	gcc \
	git \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
USER airflow
ENV DBT_PROFILES_DIR=/opt/airflow/dbt
ENV PATH="/home/airflow/.local/bin:${PATH}"
RUN pip install --no-cache-dir \
	airflow-clickhouse-plugin \
	clickhouse-driver \
	clickhouse-connect \
	dbt-core==1.7.9 \
	dbt-clickhouse==1.7.6 \
	"pyiceberg[s3fs]>=0.6.0" \
	pyarrow \
	s3fs \
	fsspec \
	aiohttp \
	boto3