name: clickhouse_dbt_demo
version: "1.0"
config-version: 2

profile: clickhouse_dbt_demo

model-paths: ["models"]
seed-paths: ["seeds"]


models:
  clickhouse_dbt_demo:
    bronze:
      +materialized: table


seeds:
  +quote_columns: false
  clickhouse_dbt_demo:
    raw_iot_data:
      +column_types:
        entity_id: String
        state: Float64
        last_changed: DateTime('UTC')
    raw_meteo_data:
      +column_types:
        Time: DateTime
        Temperature: Float64
        Humidity: Float64
        pressure: Float64
        wind_speed: Float64
        wind_direction: Float64
        precipitation: Float64
        uv_index: Nullable(Float64)
        light_status: Nullable(String)
        radiation_flux: Float64
