version: 2

models:
  - name: dim_device
    description: "Dimension table for devices"
    columns:
      - name: DeviceKey
        description: "Surrogate key for device"
        tests:
          - unique
          - not_null
      - name: Brand
        description: "Device brand"
        tests:
          - not_null
      - name: Model
        description: "Device model"
        tests:
          - not_null
      - name: MinPower
        description: "Minimum power (>=0)"
        tests:
          - expression_is_true_clickhouse:
              column_name: MinPower
              expression: "MinPower >= 0"
      - name: InstallationDate
        description: "Installation date"
        tests:
          - not_null
      - name: ValidTo
        description: "Validity end date (default '9999-12-31')"

  - name: dim_location
    description: "Dimension table for locations"
    columns:
      - name: LocationKey
        description: "Surrogate key for location"
        tests:
          - unique
          - not_null
      - name: DeviceLocation
        description: "Location of the device"
        tests:
          - not_null
      - name: ClosestWeatherStation
        description: "Closest weather station"
        tests:
          - not_null
      - name: PricingRegion
        description: "Pricing region"
        tests:
          - not_null
      - name: ValidFrom
        description: "Start of validity"
        tests:
          - not_null
      - name: ValidTo
        description: "End of validity (default '9999-12-31')"
        tests:
          - expression_is_true_clickhouse:
              column_name: ValidTo
              expression: "ValidTo >= ValidFrom"

  - name: dim_time
    description: "Dimension table for time (hour grain)"
    columns:
      - name: TimeKey
        description: "Surrogate key for time"
        tests:
          - unique
          - not_null
      - name: FullDate
        description: "Date component"
        tests:
          - not_null
      - name: Year
        description: "Year"
        tests:
          - expression_is_true_clickhouse:
              column_name: Year
              expression: "Year >= 2000"
      - name: Month
        description: "Month"
        tests:
          - expression_is_true_clickhouse:
              column_name: Month
              expression: "Month BETWEEN 1 AND 12"
      - name: Day
        description: "Day of month"
        tests:
          - expression_is_true_clickhouse:
              column_name: Day
              expression: "Day BETWEEN 1 AND 31"
      - name: DayOfWeek
        description: "Day of week"
        tests:
          - expression_is_true_clickhouse:
              column_name: DayOfWeek
              expression: "DayOfWeek BETWEEN 1 AND 7"
      - name: HourOfDay
        description: "Hour of day"
        tests:
          - expression_is_true_clickhouse:
              column_name: HourOfDay
              expression: "HourOfDay BETWEEN 0 AND 23"
      - name: Season
        description: "Season name"
        tests:
          - expression_is_true_clickhouse:
              column_name: Season
              expression: "Season IN ('Winter','Spring','Summer','Autumn')"
      - name: IsHoliday
        description: "Holiday flag"
        tests:
          - expression_is_true_clickhouse:
              column_name: IsHoliday
              expression: "IsHoliday IN (0,1)"
      - name: IsWeekend
        description: "Weekend flag"
        tests:
          - expression_is_true_clickhouse:
              column_name: IsWeekend
              expression: "IsWeekend IN (0,1)"
      - name: IsPeakHour
        description: "Peak hour flag"
        tests:
          - expression_is_true_clickhouse:
              column_name: IsPeakHour
              expression: "IsPeakHour IN (0,1)"

  - name: fact_heating_energy_usage
    description: "Heating energy usage facts for devices and locations"
    columns:
      - name: FactKey
        description: "Unique row identifier"
        tests:
          - unique
          - not_null
      - name: TimeKey
        description: "Foreign key to time dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: TimeKey
      - name: DeviceKey
        description: "Foreign key to device dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_device')
              field: DeviceKey
      - name: LocationKey
        description: "Foreign key to location dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_location')
              field: LocationKey
      - name: ElectricityPrice
        description: "Electricity price at the time"
      - name: ASHP_Power
        description: "Power consumption of ASHP system"
      - name: Boiler_Power
        description: "Power consumption of the boiler"
      - name: Air_Drier_Power
        description: "Power consumption of air drier"
      - name: Boiler_Voltage
        description: "Boiler voltage"
      - name: IndoorTemp
        description: "Indoor temperature (째C)"
      - name: IndoorHumidityPerc
        description: "Indoor humidity percentage"
      - name: IndoorHumidityAbs
        description: "Indoor absolute humidity"
      - name: WC_HumidityAbs
        description: "WC absolute humidity"
      - name: WC_Temp
        description: "WC temperature (째C)"
      - name: OutdoorTemp
        description: "Outdoor temperature (째C)"
      - name: DewPoint
        description: "Calculated dew point (째C)"
      - name: OutdoorHumidityPerc
        description: "Outdoor humidity percentage"
      - name: CloudCoverage
        description: "Cloud coverage percentage"
      - name: UV_Index
        description: "UV index level"
      - name: AirPressure_mmHg
        description: "Air pressure in millimeters of mercury"
      - name: WindDir
        description: "Wind direction (degrees)"
      - name: WindGustSpeed_ms
        description: "Wind gust speed (m/s)"
      - name: WindSpeed_ms
        description: "Average wind speed (m/s)"
      - name: WeatherCondition
        description: "Weather condition description"

    tests:
      # --- Custom data validity tests ---
      - expression_is_true_clickhouse:
          column_name: ASHP_Power
          expression: "ASHP_Power >= 0"

      - expression_is_true_clickhouse:
          column_name: IndoorHumidityPerc
          expression: "IndoorHumidityPerc BETWEEN 0 AND 100"

      - expression_is_true_clickhouse:
          column_name: OutdoorHumidityPerc
          expression: "OutdoorHumidityPerc BETWEEN 0 AND 100"

      - expression_is_true_clickhouse:
          column_name: UV_Index
          expression: "UV_Index >= 0"

      - expression_is_true_clickhouse:
          column_name: AirPressure_mmHg
          expression: "AirPressure_mmHg BETWEEN 600 AND 800"

      - expression_is_true_clickhouse:
          column_name: WindDir
          expression: "WindDir BETWEEN 0 AND 360"

      - expression_is_true_clickhouse:
          column_name: WindSpeed_ms
          expression: "WindSpeed_ms >= 0"

      - expression_is_true_clickhouse:
          column_name: WindGustSpeed_ms
          expression: "WindGustSpeed_ms >= 0"

      # --- Basic null checks ---
      - not_null:
          column_name: ASHP_Power
      
